### ISSUE TITLE
html tables with alternating colors could use a touch-up

### ISSUE THREAD

**Issue by areedc** [data-science-work/solarized-light-jupyter-theme#1]
![solarized_example](https://user-images.githubusercontent.com/38753340/39299937-5ec48624-494a-11e8-8e32-d1309efa4d5c.png)

First! Thanks for this! I didn't really want to mess with the jupyter themes module and this fit my need perfectly. I just wonder about one thing. How can I fix the pandas tables so that they vary from two better colors in the solarized theme?

**Comment by redeemefy** [comment]
@areedc you can inspect the table to find out what CSS classes you can target to change colors.

**Comment by diazgilberto** [comment]
The #2 closes issue #1.

**Comment by redeemefy** [comment]
The #2 closes #1.
